### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by meypod** [meypod/al-azan#23]
## current objective
- [ ] make sure 1.17.0 is stable before releasing

### main priority
- [ ] silent mode after adhan
- [ ] add vibration only mode for adhan
- [ ] fix volume button bug

### medium priority
- [ ] select which adhans/reminders to bypass DnD instead of all or nothing

### low priority
- add city name to widget or upcoming notification
- add font size settings
- make monthly view more configurable
